.catalog:
  version: v1.12-rancher0
  maximum_rancher_version: v1.2.0-pre4
  questions:
  - variable: MANAGER_SCALE
    label: Number of Managers
    description: Desired number of managers to participating in service orchestration. This dictates host resilience.
    required: true
    default: 3
    type: enum
    options:
    - 1
    - 3
    - 5
    - 7
    - 9
  - variable: LISTEN_INTERFACE
    label: Host Interface Name
    description: "Host interface for overlay network to listen on. Required iff CATTLE_AGENT_IP isn't set to a private IP address on all hosts"
    required: false
    type: string
swarmkit-mon:
  health_check:
    request_line: GET /ping HTTP/1.0
    port: 2378
    interval: 15000
    response_timeout: 10000
    healthy_threshold: 1
    unhealthy_threshold: 2
